export default {
  // Profile ----------------------------------------------------------------------------
  orgTableHead: [
    { id: 'id', label: '№', alignRight: false },
    { id: 'orgMobileNumber', label: 'Утасны дугаар', alignRight: false },
    { id: 'name', label: 'Нэр', alignRight: false },
    { id: 'email', label: 'Имэйл', alignRight: false },
    { id: 'register', label: 'Регистр', alignRight: false },
    { id: 'description', label: 'Товч танилцуулга', alignRight: false },
    { id: 'employee', label: 'Ажилтан 1', alignRight: false },
    { id: 'role', label: 'Албан тушаал', alignRight: false },
    { id: 'mobileNumber', label: 'Утасны дугаар', alignRight: false },
    { id: 'employee', label: 'Ажилтан 2', alignRight: false },
    { id: 'role', label: 'Албан тушаал', alignRight: false },
    { id: 'mobileNumber', label: 'Утасны дугаар', alignRight: false },
    { id: 'action', label: 'Үйлдэл', alignRight: false },
  ],
  permissionTableHead: [
    { id: 'id', label: '№', alignRight: false },
    { id: 'mobilenumber', label: 'Утасны дугаар', alignRight: false },
    { id: 'name', label: 'Нэр', alignRight: false },
    { id: 'email', label: 'Имэйл', alignRight: false },
    { id: 'register', label: 'Регистр', alignRight: false },
    { id: 'type', label: 'Төлөв', alignRight: false },
    { id: 'degree', label: 'Түвшин', alignRight: false },
    { id: 'role', label: 'Эрх', alignRight: false },
    { id: 'createdDate', label: 'Бүртгүүлсэн огноо', alignRight: false },
    { id: 'note', label: 'Тэмдэглэл', alignRight: false },
    { id: 'action', label: 'Үйлдэл', alignRight: false },
  ],
  specialTableHead: [
    { id: 'id', label: '№', alignRight: false },
    { id: 'mobileNumber', label: 'Утасны дугаар', alignRight: false },
    { id: 'name', label: 'Нэр', alignRight: false },
    { id: 'register', label: 'Регистер', alignRight: false },
    { id: 'amount', label: 'Мөнгөн дүн', alignRight: false },
    { id: 'createdDate', label: 'Бүртгүүлсэн огноо', alignRight: false },
    { id: 'description', label: 'Тайлбар', alignRight: false },
    { id: 'action', label: '#', alignRight: false },
  ],
  merchantsTableHead: [
    { id: 'id', label: '№', alignRight: false },
    { id: 'name', label: 'Нэр', alignRight: false },
    { id: 'role', label: 'Эрх', alignRight: false },
    { id: 'shop', label: 'Дэлгүүр', alignRight: false },
    { id: 'branch', label: 'Салбар', alignRight: false },
    { id: 'isActive', label: 'Идэвхтэй эсэх', alignRight: false },
    { id: 'comeDetachmentAt', label: 'Үйлдэл', alignRight: true },
  ],
  // Loan ----------------------------------------------------------------------------
  givenLoanTableHead: [
    { id: 'id', label: '№', alignRight: false },
    { id: 'code', label: 'Код', alignRight: false },
    { id: 'name', label: 'Нэр', alignRight: false },
    { id: 'phone', label: 'Салбарын нэр', alignRight: false },
    { id: 'duration', label: 'Дэлгүүр', alignRight: false },
    { id: 'startDate', label: 'Зээлсэн дүн', alignRight: false },
    { id: 'endDate', label: 'Үлдэгдэл', alignRight: false },
    { id: 'spc', label: 'Алданги', alignRight: false },
    { id: 'annual', label: 'Ангилал', alignRight: false },
    { id: 'cancel', label: 'Зээл олгосон огноо', alignRight: false },
    { id: 'isStake', label: 'Дуусах', alignRight: false },
    { id: 'description', label: 'Төлөв', alignRight: false },
    { id: 'interval', label: 'Статус', alignRight: false },
    { id: 'action', label: 'Үйлдэл', alignRight: true },
  ],
  glPopupTableHead: [
    { id: 'id', label: 'Нэхэмжлэлийн дугаар', alignRight: false },
    { id: 'name', label: 'Төрөл', alignRight: false },
    { id: 'credit', label: 'Кредит', alignRight: false },
    { id: 'debit', label: 'Дебит', alignRight: false },
    { id: 'date', label: 'Огноо', alignRight: false },
    { id: 'description', label: 'Тайлбар', alignRight: false },
    { id: 'Action', label: 'Үйлдэл', alignRight: true },
  ],
  dueLoanTableHead: [
    { id: 'id', label: '№', alignRight: false },
    { id: 'code', label: 'Код', alignRight: false },
    { id: 'name', label: 'Нэр', alignRight: false },
    { id: 'phone', label: 'Салбарын нэр', alignRight: false },
    { id: 'duration', label: 'Дэлгүүр', alignRight: false },
    { id: 'startDate', label: 'Зээлсэн дүн', alignRight: false },
    { id: 'endDate', label: 'Үлдэгдэл', alignRight: false },
    { id: 'spc', label: 'Алданги', alignRight: false },
    { id: 'annual', label: 'Ангилал', alignRight: false },
    { id: 'cancel', label: 'Зээл олгосон огноо', alignRight: false },
    { id: 'isStake', label: 'Дуусах', alignRight: false },
    { id: 'description', label: 'Төлөв', alignRight: false },
    { id: 'interval', label: 'Статус', alignRight: false },
    { id: 'action', label: 'Үйлдэл', alignRight: true },
  ],
  dlPopupTableHead: [
    { id: 'id', label: 'Нэхэмжлэлийн дугаар', alignRight: false },
    { id: 'name', label: 'Төрөл', alignRight: false },
    { id: 'phone', label: 'Кредит', alignRight: false },
    { id: 'duration', label: 'Дебит', alignRight: false },
    { id: 'startDate', label: 'Огноо', alignRight: false },
    { id: 'endDate', label: 'Тайлбар', alignRight: false },
    { id: 'spc', label: 'Үйлдэл', alignRight: true },
  ],
  cancelledLoanTableHead: [
    { id: 'id', label: '№', alignRight: false },
    { id: 'code', label: 'Код', alignRight: false },
    { id: 'name', label: 'Нэр', alignRight: false },
    { id: 'phone', label: 'Салбарын нэр', alignRight: false },
    { id: 'duration', label: 'Дэлгүүр', alignRight: false },
    { id: 'startDate', label: 'Зээлсэн дүн', alignRight: false },
    { id: 'endDate', label: 'Үлдэгдэл', alignRight: false },
    { id: 'spc', label: 'Алданги', alignRight: false },
    { id: 'annual', label: 'Ангилал', alignRight: false },
    { id: 'cancel', label: 'Зээл олгосон огноо', alignRight: false },
    { id: 'isStake', label: 'Дуусах', alignRight: false },
    { id: 'description', label: 'Төлөв', alignRight: false },
    { id: 'interval', label: 'Статус', alignRight: false },
    { id: 'cancelDate', label: 'Цуцалсан огноо', alignRight: false },
    { id: 'action', label: 'Үйлдэл', alignRight: true },
  ],
  clPopupTableHead: [
    { id: 'id', label: 'Нэхэмжлэлийн дугаар', alignRight: false },
    { id: 'name', label: 'Төрөл', alignRight: false },
    { id: 'phone', label: 'Кредит', alignRight: false },
    { id: 'duration', label: 'Дебит', alignRight: false },
    { id: 'startDate', label: 'Огноо', alignRight: false },
    { id: 'endDate', label: 'Тайлбар', alignRight: false },
    { id: 'spc', label: 'Үйлдэл', alignRight: true },
  ],
  pendingLoanTableHead: [
    { id: 'id', label: '№', alignRight: false },
    { id: 'code', label: 'Код', alignRight: false },
    { id: 'name', label: 'Нэр', alignRight: false },
    { id: 'phone', label: 'Салбарын нэр', alignRight: false },
    { id: 'duration', label: 'Дэлгүүр', alignRight: false },
    { id: 'startDate', label: 'Зээлсэн дүн', alignRight: false },
    { id: 'endDate', label: 'Үлдэгдэл', alignRight: false },
    { id: 'cancel', label: 'Зээл олгосон огноо', alignRight: false },
    { id: 'isStake', label: 'Дуусах', alignRight: false },
    { id: 'description', label: 'Төлөв', alignRight: false },
    { id: 'interval', label: 'Статус', alignRight: false },
    { id: 'action', label: 'Үйлдэл', alignRight: true },
  ],
  plPopupTableHead: [
    { id: 'id', label: 'Нэхэмжлэлийн дугаар', alignRight: false },
    { id: 'name', label: 'Төрөл', alignRight: false },
    { id: 'phone', label: 'Кредит', alignRight: false },
    { id: 'duration', label: 'Дебит', alignRight: false },
    { id: 'startDate', label: 'Огноо', alignRight: false },
    { id: 'endDate', label: 'Тайлбар', alignRight: false },
    { id: 'spc', label: 'Үйлдэл', alignRight: true },
  ],
  // Store ----------------------------------------------------------------------------
  storeTableHead: [
    { id: 'code', label: 'Код', alignRight: false },
    { id: 'shop', label: 'Дэлгүүр', alignRight: false },
    { id: 'branchName', label: 'Салбарын нэр', alignRight: false },
    { id: 'phone', label: 'Утас', alignRight: false },
    { id: 'commision', label: 'Шимтгэл', alignRight: false },
    { id: 'paymentDate', label: 'Шилжүүлэг хийх өдөр', alignRight: false },
    { id: 'noat', label: 'НӨАТ төлөгч', alignRight: false },
    { id: 'visibility', label: 'Харагдах эсэх', alignRight: false },
    { id: 'createdDate', label: 'Үүсгэсэн огноо', alignRight: false },
    { id: 'action', label: 'Үйлдэл', alignRight: false },
  ],
  // Order ----------------------------------------------------------------------------
  orderTableHead: [
    { id: 'type', label: 'Төлөв', alignRight: false },
    { id: 'date', label: 'Огноо', alignRight: false },
    { id: 'time', label: 'Цаг', alignRight: false },
    { id: 'code', label: 'Нөхцөлийн код', alignRight: false },
    { id: 'type2', label: 'Төрөл', alignRight: false },
    { id: 'specNumber', label: 'Тусгай дугаар', alignRight: false },
    { id: 'text', label: 'Текст', alignRight: false },
    { id: 'segmentCheck', label: 'Сегментийн шалгуур', alignRight: false },
    { id: 'blacklist', label: 'Хасах', alignRight: false },
    { id: 'userCount', label: 'Сегмент илгээх хэрэглэгчид', alignRight: false },
    { id: 'segmentUser', label: 'Сегмент гаргах мэргэжилтэн', alignRight: false },
    { id: 'sender', label: 'Илгээх мэргэжилтэн', alignRight: false },
    { id: 'description', label: 'Нэмэлт тайлбар ', alignRight: false },
    { id: 'test', label: 'Test', alignRight: false },
    { id: 'segment', label: 'Segment', alignRight: false },
    { id: 'sementCount', label: 'Segment count', alignRight: false },
    { id: 'bc', label: 'BC', alignRight: false },
    { id: 'action', label: 'Үйлдэл', alignRight: false },
  ],
  bannerTableHead: [
    { id: 'id', label: 'id', alignRight: false },
    { id: 'storeId', label: 'Дэлгүүр', alignRight: false },
    { id: 'banner1', label: 'Баннер', alignRight: false },
    { id: 'banner2', label: 'Баннер', alignRight: false },
    { id: 'banner3', label: 'Баннер', alignRight: false },
    { id: 'banner4', label: 'Баннер', alignRight: false },
    { id: 'action', label: 'Үйлдэл', alignRight: false },
  ],
  searchTableHead: [
    { id: 'id', label: 'ID', alignRight: false },
    { id: 'name', label: 'Нэр', alignRight: false },
    { id: 'keywords', label: 'Түлхүүр үгс', alignRight: false },
    { id: 'sortOrder', label: 'Эрэмбэ', alignRight: false },
    { id: 'isShow', label: 'Харуулах эсэх', alignRight: false },
    { id: 'action', label: 'Үйлдэл', alignRight: false },
  ],
  typeTableHead: [
    { id: 'number', label: '№', alignRight: false },
    { id: 'checkbox', label: '', alignRight: false },
    { id: 'state', label: 'Төлөв', alignRight: false },
    { id: 'date', label: 'Огноо', alignRight: false },
    { id: 'time', label: 'Цаг', alignRight: false },
    { id: 'code', label: 'Нөхцөлийн код', alignRight: false },
    { id: 'type', label: 'Төрөл', alignRight: false },
    { id: 'unqcode', label: 'Тусгай дугаар', alignRight: false },
    { id: 'text', label: 'Текст', alignRight: false },
    { id: 'segmentFilter', label: 'Сегмэнтийн шалгуур', alignRight: false },
    { id: 'deduct', label: 'Хасах', alignRight: false },
    { id: 'userCount', label: 'Илгээх хэрэглэгчдийн тоо', alignRight: false },
    { id: 'displaySpecialist', label: 'Сегмэнт гаргах мэргэжилтэн', alignRight: false },
    { id: 'sendingSpecialist', label: 'Илгээх мэргэжилтэн', alignRight: false },
    { id: 'explanation', label: 'Нэмэлт тайлбар', alignRight: false },
    { id: 'test', label: 'Test', alignRight: false },
    { id: 'segment', label: 'Segment', alignRight: false },
    { id: 'segmentCount', label: 'Segment Count', alignRight: false },
    { id: 'bc', label: 'BC', alignRight: false },
    { id: 'action', label: 'ACTION', alignRight: false },
  ],
  typeSelectedTableHead: [
    { id: '№', label: '№', alignRight: false },
    { id: 'shop', label: 'Дэлгүүр', alignRight: false },
    { id: 'action', label: 'Үйлдэл', alignRight: false },
  ],
  // SPC ----------------------------------------------------------------------------
  SPCRateTableHead: [
    { id: 'id', label: '№', alignRight: false },
    { id: 'user', label: 'Админ', alignRight: false },
    { id: 'type', label: 'Ханш', alignRight: false },
    { id: 'createdDate', label: 'Өөрчилсөн огноо', alignRight: true },
  ],
  // Car ----------------------------------------------------------------------------
  carTableHead: [
    { id: 'id', label: '№', alignRight: false },
    { id: 'name', label: 'Овог, нэр', alignRight: false },
    { id: 'phone', label: 'Утас', alignRight: false },
    { id: 'manufacture', label: 'Үйлдвэр', alignRight: false },
    { id: 'loanAmount', label: 'Зээлийн хэмжээ', alignRight: false },
    { id: 'merchantName', label: 'Дэлгүүрийн нэр', alignRight: false },
    { id: 'description', label: 'Төлөв', alignRight: false },
    { id: 'createdDate', label: 'Үүсгэсэн огноо', alignRight: false },
    { id: 'closure', label: 'Хаалтын төлөв', alignRight: false },
    { id: 'createdUser', label: 'Үүсгэсэн админ', alignRight: false },
    { id: 'action', label: 'Үйлдэл', alignRight: true },
  ],
  // realEstate ----------------------------------------------------------------------------
  realEstateTableHead: [
    { id: 'id', label: '№', alignRight: false },
    { id: 'username', label: 'Дэлгүүрийн нэр', alignRight: false },
    { id: 'name', label: 'Овог, нэр', alignRight: false },
    { id: 'phone', label: 'Утас', alignRight: false },
    { id: 'country', label: 'Үүсгэсэн огноо', alignRight: false },
    { id: 'manufacture', label: 'Зээлийн хэмжээ', alignRight: false },
    { id: 'color', label: 'Төлөв', alignRight: false },
    { id: 'closure', label: 'Хаалтын төлөв', alignRight: false },
    { id: 'loanAmount', label: 'Зээл дуусах огноо', alignRight: false },
    { id: 'action', label: 'Үйлдэл', alignRight: true },
  ],
};
